### ISSUE TITLE
[IDEA] Only show bundles with actual ebooks inside

### ISSUE THREAD

**Issue by maluramichael** [DMarby/humblebundle-ebook-downloader#4]

**Comment by Zach4422** [comment]
Or what about an option to download music too?

**Comment by jlongman** [comment]
The script will download music, it really doesn't care about format, but you need to know what bundles have it.   IIRC wouldn't be impossible to search all bundles to find matching formats, just wasn't necessary for books since they have 'book' in the title.

E.g. Indie Bundle 13 has mp3  and flac soundtracks, so I used this on my version of the script: 
`node index.js -a 'auth_token_goes_here' -m indie -f mp3`

**Comment by DMarby** [comment]
This has been implemented.
